blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discuss with the Omni Community on Discord
    url: https://discord.gg/omnidotdev
    about: Ask general questions, share ideas, or chat with the team and community
  - name: ðŸ“˜ Contribution Guide
    url: https://docs.omni.dev/contributing/overview
    about: Learn how to contribute to the Omni ecosystem
  - name: ðŸ”’ Security Policy
    url: mailto:security@omni.dev
    about: Report sensitive security vulnerabilities privately
